### ISSUE TITLE
Linked List Problem in java

### ISSUE THREAD

**Issue by AvinashChourasia** [pratyush-patwa/hacktoberfest2022#25]
Hi @pratyush-patwa  , I want to add the some good problems of Linked List in Java. Can you assign this task to me under hacktoberfest label.

**Comment by pratyush-patwa** [comment]
@AvinashChourasia  added

**Comment by AvinashChourasia** [comment]
Hi @pratyush-patwa , please check my PRs.

**Comment by AvinashChourasia** [comment]
Your repos has been excluded from Hacktoberfest 2022

**Comment by pratyush-patwa** [comment]
@AvinashChourasia  is it?

**Comment by AvinashChourasia** [comment]
Yes

**Comment by AvinashChourasia** [comment]
Mail to the Hacktoberfest Organising commitee. So, they can resolve this problem.
